### PR TITLE
Fix chat crash in Chromium 150

### LINKED ISSUE #3133: Bug Report: Chat crashes after sending a message in Chrome/Edge 150
### This issue is for a: (mark with an `x`)
[x]  bug report -> please search issues before submitting
[]  feature request
[] documentation issue or request
[] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce

1. Open the deployed app in Chrome or Edge 150.0.0.0.
2. Send a message in the chat.
3. The response is returned successfully, but the UI crashes during rendering and React Router displays its default error page.

The same deployment works correctly in Chrome and Edge 149.0.0.0.

### Any log messages given by the failure

```text
TypeError: p is not a function

React Router caught the following error during render
TypeError: p is not a function
```

### Expected/desired behavior

The chat response should render normally without the application crashing.

### OS and Version?

Chrome 149.0.0.0: works
Chrome 150.0.0.0: fails
Edge 149.0.0.0: works
Edge 150.0.0.0: fails

### Mention any other details that might be useful

The issue appears to be caused by these effects in [`Chat.tsx`](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/frontend/src/pages/chat/Chat.tsx#L368-L369):
```typescript
useEffect(() => chatMessageStreamEnd.current?.scrollIntoView({ behavior: "smooth" }), [isLoading]);
useEffect(() => chatMessageStreamEnd.current?.scrollIntoView({ behavior: "auto" }), [streamedAnswers]);
```

### PR DESCRIPTION
**Pull request by dillyfishh**
## Purpose

Fixes #3133.

Chromium 150.0.0 changed `scrollIntoView()` to return a Promise. The chat page's `useEffect` callbacks implicitly returned that value, causing React to treat the Promise as an effect cleanup function and crash after a message was sent.

This change updates the effects to use block bodies so they return nothing.

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[X] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[X] No
```

## Type of change

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [x] The current tests all pass (`python -m pytest`).
- [ ] I added tests that prove my fix is effective or that my feature works
- [ ] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [ ] I ran `ty check` to check for type errors
- [ ] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Comment by gitstua** [comment]
Confirming - this fixed the issue for us in latest Microsoft Edge 150.0.x.x

cc @pamelafox - this issue probably affected lots of your customers using chromium browsers so tagging for your 👀

**Comment by pamelafox** [comment]
Thank you!

**Review by pamelafox — APPROVED** [review]
Thank you!
