### ISSUE TITLE
Bug Report: Chat crashes after sending a message in Chrome/Edge 150

### ISSUE THREAD

**Issue by dillyfishh** [Azure-Samples/azure-search-openai-demo#3133]
### This issue is for a: (mark with an `x`)
[x]  bug report -> please search issues before submitting
[]  feature request
[] documentation issue or request
[] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce

1. Open the deployed app in Chrome or Edge 150.0.0.0.
2. Send a message in the chat.
3. The response is returned successfully, but the UI crashes during rendering and React Router displays its default error page.

The same deployment works correctly in Chrome and Edge 149.0.0.0.

### Any log messages given by the failure

```text
TypeError: p is not a function

React Router caught the following error during render
TypeError: p is not a function
```

### Expected/desired behavior

The chat response should render normally without the application crashing.

### OS and Version?

Chrome 149.0.0.0: works
Chrome 150.0.0.0: fails
Edge 149.0.0.0: works
Edge 150.0.0.0: fails

### Mention any other details that might be useful

The issue appears to be caused by these effects in [`Chat.tsx`](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/frontend/src/pages/chat/Chat.tsx#L368-L369):
```typescript
useEffect(() => chatMessageStreamEnd.current?.scrollIntoView({ behavior: "smooth" }), [isLoading]);
useEffect(() => chatMessageStreamEnd.current?.scrollIntoView({ behavior: "auto" }), [streamedAnswers]);
```

**Comment by TB-Dipta** [comment]
I'm having the same issue and am looking forward to a solution.

**Comment by dillyfishh** [comment]
> I'm having the same issue and am looking forward to a solution.

I have raised a PR that solves this issue, take a look at [#3134 ](https://github.com/Azure-Samples/azure-search-openai-demo/pull/3134)

**Comment by charlidog** [comment]
Great work  @dillyfishh for raising this and the associated PR to resolve it.

Also found same issue for users using latest `Microsoft Edge 150.0.7871.47` - we could also probably improve the error checking in `chat.tsx`

The code in your PR resolved the issue for us

**Comment by bf-2026** [comment]
Really impressive. I would have had no clue where to watch in the first place to solve that issue! @dillyfishh
